{{ if and (index .Cluster.ConfigItems "spotio_account_id") (index .Cluster.ConfigItems "spotio_access_token") }}
{{ if spotIONodePools .Cluster.NodePools }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotinst-kubernetes-cluster-controller
  namespace: kube-system
  labels:
    application: spotinst-kubernetes-cluster-controller
    component: "ocean"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: spotinst-kubernetes-cluster-controller # TODO: this label name is REQUIRED by the controller
      component: "ocean"
  template:
    metadata:
      labels:
        application: spotinst-kubernetes-cluster-controller
        component: "ocean"
      annotations:
        config/hash: {{"secret.yaml" | manifestHash}}
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      # TODO: run on master?
      # nodeSelector:
      #   node.kubernetes.io/role: master
      containers:
      - name: controller
        image: pierone.stups.zalan.do/teapot/spotinst-kubernetes-cluster-controller:1.0.72
        env:
        - name: MEM_TOTAL_KB
          valueFrom:
            resourceFieldRef:
              divisor: 1Ki
              resource: limits.memory
        - name: JAVA_OPTS
          value: "-XX:+ExitOnOutOfMemoryError"
        - name: SPOTINST_TOKEN
          valueFrom:
            secretKeyRef:
              key: spotinst.token
              name: spotinst-kubernetes-cluster-controller
        - name: SPOTINST_ACCOUNT
          value: "{{ .Cluster.ConfigItems.spotio_account_id }}"
        - name: CLUSTER_IDENTIFIER
          value: "{{ .Cluster.LocalID }}"
        - name: DISABLE_AUTO_UPDATE
          value: "true"
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 4401
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 4401
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: "{{ .Cluster.ConfigItems.spotio_ocean_controller_cpu }}"
            memory: "{{ .Cluster.ConfigItems.spotio_ocean_controller_memory }}"
          requests:
            cpu: "{{ .Cluster.ConfigItems.spotio_ocean_controller_cpu }}"
            memory: "{{ .Cluster.ConfigItems.spotio_ocean_controller_memory }}"
      serviceAccountName: spotinst-kubernetes-cluster-controller
      tolerations:
      - key: node.kubernetes.io/role
        value: master
        effect: NoSchedule
{{ end }}
{{ end }}
