kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: readonly
subjects:
- kind: Group
  name: ReadOnly
  apiGroup: rbac.authorization.k8s.io
{{- if eq .Cluster.ConfigItems.okta_auth_enabled "true" }}
- kind: Group
  name: "okta:common/engineer"
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: "okta:common/collaborator"
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: "okta:common/read-only"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
